Add e2e tests
ollyrowe/whittle pull request #106
Opened 2022-12-11 23:05 UTC by ollyrowe

2022-12-15 23:30 UTC, emilielake commented on cypress/e2e/hard-mode.cy.ts
> +        // If this tile doesn't for part of the solution
*form

2022-12-15 23:40 UTC, emilielake commented on cypress/e2e/spell-word.cy.ts
> +  it("displays an incorrect as grey", () => {
word

2022-12-15 23:53 UTC, emilielake requested changes
See comments

2022-12-16 00:01 UTC, ollyrowe commented on cypress/e2e/yesterdays-game.cy.ts
> +      }
Creating new issue

2022-12-16 00:20 UTC, emilielake approved these changes

2022-12-16 00:20 UTC, merged

2022-12-24 16:52 UTC, ollyrowe commented
:tada: This PR is included in version 1.26.0 :tada:

The release is available on [GitHub release](https://github.com/ollyrowe/whittle/releases/tag/v1.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: